version: '3.8'

services:
  server:
    build: ./server
    container_name: server 
    ports:
      - "3001:3001"
    environment: 
      - mongodb+srv://lgopikrishna84:lgopikrishna@cluster.btodjyc.mongodb.net/
  client:
    build: ./client
    container_name: client
    ports :
     - "3000:80"